---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pixton-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /home/volumes/pixton
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pixton-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pixton-data
